server:
  port: 8081
  servlet:
    context-path: /experian

spring:
  data:
   mongodb:
     uri: mongodb://localhost:27017/experian
     database: experian
  application:
    name: discovery-client

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    health-check:
      enabled: true
