spring:
  application:
    name: credit-score-app
  config:
    activate:
      on-profile:
    import: configserver:http://localhost:8888

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    health-check:
      enabled: true
